In [1]:
import numpy as np
np.__version__

'2.2.3'

In [4]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [5]:
type(array1)

numpy.ndarray

In [7]:
array2=np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array3d=np.array([[
                    [1,2],
                    [3,4]
                ],
    [
        [5,6],
        [7,8]
    ]
])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
array3ex=np.array([
                    [
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                    ],
                  [
                      [10,11,12],
                      [13,14,15],
                      [16,17,18]
                  ]
                  ])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
array3ex.shape

(2, 3, 3)

In [14]:
array4d=np.array([
    [
        [
            [1,2],
            [3,4],
            [5,7]
            
        ],
        [
            [2,4],
            [4,6],
            [7,5],
        ],
        [
            [6,7],
            [9,8],
            [8,6]
        ]
    ],
    [
        [
            [7,4],
            [2,1],
            [7,8],
        ],
        [
            [5,4],
            [8,5],
            [9,3]
        ],
        [
            [6,3],
            [9,5],
            [0,5]
        ]
    ]
])
array4d

array([[[[1, 2],
         [3, 4],
         [5, 7]],

        [[2, 4],
         [4, 6],
         [7, 5]],

        [[6, 7],
         [9, 8],
         [8, 6]]],


       [[[7, 4],
         [2, 1],
         [7, 8]],

        [[5, 4],
         [8, 5],
         [9, 3]],

        [[6, 3],
         [9, 5],
         [0, 5]]]])

In [15]:
array4d.shape

(2, 3, 3, 2)

In [18]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [20]:
arrayex5.shape

(3,)

In [22]:
arr=np.array([10,20,30,40,50])
mean_val=np.mean(arr)
std_dev=np.std(arr)
max_val=np.max(arr)
min_val=np.min(arr)
print("Array:",arr)
print("Mean:",mean_val)
print(f"Standard deviation:{std_dev:.2f}")
print("Maximum:",max_val)
print("Minimum:",min_val)

Array: [10 20 30 40 50]
Mean: 30.0
Standard deviation:14.14
Maximum: 50
Minimum: 10
